export const ISSUE_TOKEN_FOR_USER = Symbol('ISSUE_TOKEN_FOR_USER');
export const VALIDATE_APPLICATION_TOKEN = Symbol('VALIDATE_APPLICATION_TOKEN');
export const LOGOUT_USER = Symbol('LOGOUT_USER');
export const CREATE_GOOGLE_AUTH_REDIRECT = Symbol('CREATE_GOOGLE_AUTH_REDIRECT');
export const HANDLE_GOOGLE_CALLBACK = Symbol('HANDLE_GOOGLE_CALLBACK');
