export const ISSUE_TOKEN_FOR_USER = Symbol('ISSUE_TOKEN_FOR_USER');
export const VALIDATE_APPLICATION_TOKEN = Symbol('VALIDATE_APPLICATION_TOKEN');
export const LOGOUT_USER = Symbol('LOGOUT_USER');
export const CREATE_AUTH_REDIRECT = Symbol('CREATE_AUTH_REDIRECT');
export const EXCHANGE_AUTH_CODE_FOR_ACCESS_TOKEN = Symbol(
  'EXCHANGE_AUTH_CODE_FOR_ACCESS_TOKEN',
);
